import { CardProps } from '@/components/Home/Card/Card';
import card1 from '#/images/img-carousel1.png';
import card2 from '#/images/img-carousel2.png';
import card3 from '#/images/img-carousel3.png';

export const MOCK_DATA: CardProps['item'][] = [
  {
    id: 1,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 1,
    bannerImageUrl: card1.src,
    rating: 5,
    reviewCount: 793,
  },
  {
    id: 2,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 2,
    bannerImageUrl: card2.src,
    rating: 5,
    reviewCount: 793,
  },
  {
    id: 3,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 3,
    bannerImageUrl: card3.src,
    rating: 5,
    reviewCount: 793,
  },
  {
    id: 4,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 4,
    bannerImageUrl: card1.src,
    rating: 5,
    reviewCount: 793,
  },
  {
    id: 5,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 5,
    bannerImageUrl: card2.src,
    rating: 5,
    reviewCount: 793,
  },
  {
    id: 6,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 6,
    bannerImageUrl: card2.src,
    rating: 5,
    reviewCount: 793,
  },
  {
    id: 7,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 7,
    bannerImageUrl: card2.src,
    rating: 5,
    reviewCount: 793,
  },
  {
    id: 8,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 8,
    bannerImageUrl: card2.src,
    rating: 5,
    reviewCount: 793,
  },
  {
    id: 9,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 9,
    bannerImageUrl: card2.src,
    rating: 5,
    reviewCount: 793,
  },
  {
    id: 10,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 10,
    bannerImageUrl: card2.src,
    rating: 5,
    reviewCount: 793,
  },
  {
    id: 11,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 11,
    bannerImageUrl: card2.src,
    rating: 5,
    reviewCount: 793,
  },
  {
    id: 12,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 12,
    bannerImageUrl: card2.src,
    rating: 5,
    reviewCount: 793,
  },
  {
    id: 13,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 13,
    bannerImageUrl: card2.src,
    rating: 5,
    reviewCount: 793,
  },
  {
    id: 14,
    userId: 0,
    title: '함께 배우면 즐거운 스트릿 댄스',
    description: 'ㅁㄴㅇ',
    category: '투어',
    price: 14,
    bannerImageUrl: card2.src,
    rating: 5,
    reviewCount: 793,
  },
];
